package telas;

import classes.Dente;
import classes.DenteDAO;
import classes.Odontograma;
import classes.OdontogramaDAO;
import classes.PacienteDAO;
import java.awt.event.KeyEvent;
import java.util.List;
import javax.swing.JOptionPane;

public class TelaCadastroOdontograma extends javax.swing.JFrame {

    private TelaPrincipal telaPrincipal;

    public void MostraTela(TelaPrincipal obj) {
        this.telaPrincipal = obj;
        setVisible(true);
    }

    public TelaCadastroOdontograma() {
        initComponents();
        geraAcessibilidade();
        rdbtnAdulto.setSelected(true);
        lblImagem2_1.setVisible(false);
        lblImagem2_2.setVisible(false);
        lblDente51.setVisible(false);
        lblDente52.setVisible(false);
        lblDente53.setVisible(false);
        lblDente54.setVisible(false);
        lblDente55.setVisible(false);
        lblDente61.setVisible(false);
        lblDente62.setVisible(false);
        lblDente63.setVisible(false);
        lblDente64.setVisible(false);
        lblDente65.setVisible(false);
        lblDente71.setVisible(false);
        lblDente72.setVisible(false);
        lblDente73.setVisible(false);
        lblDente74.setVisible(false);
        lblDente75.setVisible(false);
        lblDente81.setVisible(false);
        lblDente82.setVisible(false);
        lblDente83.setVisible(false);
        lblDente84.setVisible(false);
        lblDente85.setVisible(false);
        rbtnDente51.setVisible(false);
        rbtnDente52.setVisible(false);
        rbtnDente53.setVisible(false);
        rbtnDente54.setVisible(false);
        rbtnDente55.setVisible(false);
        rbtnDente61.setVisible(false);
        rbtnDente62.setVisible(false);
        rbtnDente63.setVisible(false);
        rbtnDente64.setVisible(false);
        rbtnDente65.setVisible(false);
        rbtnDente71.setVisible(false);
        rbtnDente72.setVisible(false);
        rbtnDente73.setVisible(false);
        rbtnDente74.setVisible(false);
        rbtnDente75.setVisible(false);
        rbtnDente81.setVisible(false);
        rbtnDente82.setVisible(false);
        rbtnDente83.setVisible(false);
        rbtnDente84.setVisible(false);
        rbtnDente85.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        lblCadastroPaciente = new javax.swing.JLabel();
        btnCancelar = new javax.swing.JButton();
        lblAnotacoes = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtAnotacoes = new javax.swing.JTextArea();
        lblTipo = new javax.swing.JLabel();
        rdbtnAdulto = new javax.swing.JRadioButton();
        rdbtnInfantil = new javax.swing.JRadioButton();
        btnSalvar = new javax.swing.JButton();
        rbtnDente28 = new javax.swing.JRadioButton();
        rbtnDente27 = new javax.swing.JRadioButton();
        rbtnDente26 = new javax.swing.JRadioButton();
        rbtnDente25 = new javax.swing.JRadioButton();
        rbtnDente24 = new javax.swing.JRadioButton();
        rbtnDente23 = new javax.swing.JRadioButton();
        rbtnDente22 = new javax.swing.JRadioButton();
        rbtnDente21 = new javax.swing.JRadioButton();
        rbtnDente14 = new javax.swing.JRadioButton();
        rbtnDente15 = new javax.swing.JRadioButton();
        rbtnDente16 = new javax.swing.JRadioButton();
        rbtnDente17 = new javax.swing.JRadioButton();
        rbtnDente18 = new javax.swing.JRadioButton();
        rbtnDente11 = new javax.swing.JRadioButton();
        rbtnDente12 = new javax.swing.JRadioButton();
        rbtnDente13 = new javax.swing.JRadioButton();
        rbtnDente35 = new javax.swing.JRadioButton();
        rbtnDente34 = new javax.swing.JRadioButton();
        rbtnDente33 = new javax.swing.JRadioButton();
        rbtnDente32 = new javax.swing.JRadioButton();
        rbtnDente31 = new javax.swing.JRadioButton();
        rbtnDente44 = new javax.swing.JRadioButton();
        rbtnDente45 = new javax.swing.JRadioButton();
        rbtnDente47 = new javax.swing.JRadioButton();
        rbtnDente38 = new javax.swing.JRadioButton();
        rbtnDente37 = new javax.swing.JRadioButton();
        rbtnDente36 = new javax.swing.JRadioButton();
        rbtnDente41 = new javax.swing.JRadioButton();
        rbtnDente42 = new javax.swing.JRadioButton();
        rbtnDente43 = new javax.swing.JRadioButton();
        rbtnDente46 = new javax.swing.JRadioButton();
        rbtnDente48 = new javax.swing.JRadioButton();
        lblImagem1_2 = new javax.swing.JLabel();
        lblImagem1_1 = new javax.swing.JLabel();
        lblDente11 = new javax.swing.JLabel();
        lblDente12 = new javax.swing.JLabel();
        lblDente13 = new javax.swing.JLabel();
        lblDente14 = new javax.swing.JLabel();
        lblDente15 = new javax.swing.JLabel();
        lblDente16 = new javax.swing.JLabel();
        lblDente17 = new javax.swing.JLabel();
        lblDente18 = new javax.swing.JLabel();
        lblDente21 = new javax.swing.JLabel();
        lblDente22 = new javax.swing.JLabel();
        lblDente23 = new javax.swing.JLabel();
        lblDente24 = new javax.swing.JLabel();
        lblDente25 = new javax.swing.JLabel();
        lblDente26 = new javax.swing.JLabel();
        lblDente27 = new javax.swing.JLabel();
        lblDente28 = new javax.swing.JLabel();
        lblDente36 = new javax.swing.JLabel();
        lblDente37 = new javax.swing.JLabel();
        lblDente38 = new javax.swing.JLabel();
        lblDente31 = new javax.swing.JLabel();
        lblDente32 = new javax.swing.JLabel();
        lblDente33 = new javax.swing.JLabel();
        lblDente34 = new javax.swing.JLabel();
        lblDente35 = new javax.swing.JLabel();
        lblDente43 = new javax.swing.JLabel();
        lblDente42 = new javax.swing.JLabel();
        lblDente41 = new javax.swing.JLabel();
        lblDente44 = new javax.swing.JLabel();
        lblDente45 = new javax.swing.JLabel();
        lblDente46 = new javax.swing.JLabel();
        lblDente47 = new javax.swing.JLabel();
        lblDente48 = new javax.swing.JLabel();
        lblImagem2_1 = new javax.swing.JLabel();
        lblImagem2_2 = new javax.swing.JLabel();
        lblDente61 = new javax.swing.JLabel();
        lblDente62 = new javax.swing.JLabel();
        rbtnDente65 = new javax.swing.JRadioButton();
        lblDente63 = new javax.swing.JLabel();
        lblDente64 = new javax.swing.JLabel();
        lblDente65 = new javax.swing.JLabel();
        rbtnDente64 = new javax.swing.JRadioButton();
        rbtnDente63 = new javax.swing.JRadioButton();
        rbtnDente62 = new javax.swing.JRadioButton();
        rbtnDente61 = new javax.swing.JRadioButton();
        rbtnDente51 = new javax.swing.JRadioButton();
        lblDente51 = new javax.swing.JLabel();
        rbtnDente52 = new javax.swing.JRadioButton();
        rbtnDente53 = new javax.swing.JRadioButton();
        rbtnDente54 = new javax.swing.JRadioButton();
        rbtnDente55 = new javax.swing.JRadioButton();
        lblDente52 = new javax.swing.JLabel();
        lblDente53 = new javax.swing.JLabel();
        lblDente54 = new javax.swing.JLabel();
        lblDente55 = new javax.swing.JLabel();
        rbtnDente71 = new javax.swing.JRadioButton();
        lblDente71 = new javax.swing.JLabel();
        rbtnDente72 = new javax.swing.JRadioButton();
        rbtnDente73 = new javax.swing.JRadioButton();
        rbtnDente74 = new javax.swing.JRadioButton();
        rbtnDente75 = new javax.swing.JRadioButton();
        lblDente72 = new javax.swing.JLabel();
        lblDente73 = new javax.swing.JLabel();
        lblDente74 = new javax.swing.JLabel();
        lblDente75 = new javax.swing.JLabel();
        rbtnDente81 = new javax.swing.JRadioButton();
        lblDente81 = new javax.swing.JLabel();
        rbtnDente82 = new javax.swing.JRadioButton();
        rbtnDente83 = new javax.swing.JRadioButton();
        rbtnDente84 = new javax.swing.JRadioButton();
        rbtnDente85 = new javax.swing.JRadioButton();
        lblDente82 = new javax.swing.JLabel();
        lblDente83 = new javax.swing.JLabel();
        lblDente84 = new javax.swing.JLabel();
        lblDente85 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("SICODON");

        jPanel1.setBackground(new java.awt.Color(239, 235, 235));

        lblCadastroPaciente.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblCadastroPaciente.setText("Odontograma");

        btnCancelar.setBackground(new java.awt.Color(30, 48, 112));
        btnCancelar.setFont(new java.awt.Font("Segoe UI", 0, 35)); // NOI18N
        btnCancelar.setForeground(new java.awt.Color(255, 255, 255));
        btnCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/xis_.png"))); // NOI18N
        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        lblAnotacoes.setFont(new java.awt.Font("Segoe UI", 0, 26)); // NOI18N
        lblAnotacoes.setLabelFor(txtAnotacoes);
        lblAnotacoes.setText("Anotações:");

        txtAnotacoes.setBackground(new java.awt.Color(199, 199, 199));
        txtAnotacoes.setColumns(20);
        txtAnotacoes.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        txtAnotacoes.setRows(5);
        jScrollPane1.setViewportView(txtAnotacoes);

        lblTipo.setFont(new java.awt.Font("Segoe UI", 0, 26)); // NOI18N
        lblTipo.setText("Tipo:");

        buttonGroup1.add(rdbtnAdulto);
        rdbtnAdulto.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        rdbtnAdulto.setText("Adulto");
        rdbtnAdulto.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                rdbtnAdultoStateChanged(evt);
            }
        });
        rdbtnAdulto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdbtnAdultoActionPerformed(evt);
            }
        });

        buttonGroup1.add(rdbtnInfantil);
        rdbtnInfantil.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        rdbtnInfantil.setText("Infantil");
        rdbtnInfantil.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                rdbtnInfantilStateChanged(evt);
            }
        });
        rdbtnInfantil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdbtnInfantilActionPerformed(evt);
            }
        });

        btnSalvar.setBackground(new java.awt.Color(30, 48, 112));
        btnSalvar.setFont(new java.awt.Font("Segoe UI", 0, 35)); // NOI18N
        btnSalvar.setForeground(new java.awt.Color(255, 255, 255));
        btnSalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/salvar_.png"))); // NOI18N
        btnSalvar.setText("Salvar");
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });

        rbtnDente46.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtnDente46ActionPerformed(evt);
            }
        });

        lblImagem1_2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Odontograma1_2.png"))); // NOI18N

        lblImagem1_1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Odontograma1_1.png"))); // NOI18N

        lblDente11.setText("11");

        lblDente12.setText("12");

        lblDente13.setText("13");

        lblDente14.setText("14");

        lblDente15.setText("15");

        lblDente16.setText("16");

        lblDente17.setText("17");

        lblDente18.setText("18");

        lblDente21.setText("21");

        lblDente22.setText("22");

        lblDente23.setText("23");

        lblDente24.setText("24");

        lblDente25.setText("25");

        lblDente26.setText("26");

        lblDente27.setText("27");

        lblDente28.setText("28");

        lblDente36.setText("36");

        lblDente37.setText("37");

        lblDente38.setText("38");

        lblDente31.setText("31");

        lblDente32.setText("32");

        lblDente33.setText("33");

        lblDente34.setText("34");

        lblDente35.setText("35");

        lblDente43.setText("43");

        lblDente42.setText("42");

        lblDente41.setText("41");

        lblDente44.setText("44");

        lblDente45.setText("45");

        lblDente46.setText("46");

        lblDente47.setText("47");

        lblDente48.setText("48");

        lblImagem2_1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Odontograma2_1.png"))); // NOI18N

        lblImagem2_2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Odontograma2_2.png"))); // NOI18N

        lblDente61.setText("61");

        lblDente62.setText("62");

        lblDente63.setText("63");

        lblDente64.setText("64");

        lblDente65.setText("65");

        rbtnDente63.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtnDente63ActionPerformed(evt);
            }
        });

        lblDente51.setText("51");

        rbtnDente54.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtnDente54ActionPerformed(evt);
            }
        });

        rbtnDente55.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtnDente55ActionPerformed(evt);
            }
        });

        lblDente52.setText("52");

        lblDente53.setText("53");

        lblDente54.setText("54");

        lblDente55.setText("55");

        lblDente71.setText("71");

        lblDente72.setText("72");

        lblDente73.setText("73");

        lblDente74.setText("74");

        lblDente75.setText("75");

        lblDente81.setText("81");

        lblDente82.setText("82");

        lblDente83.setText("83");

        lblDente84.setText("84");

        lblDente85.setText("85");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblImagem1_1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblImagem1_2, javax.swing.GroupLayout.PREFERRED_SIZE, 676, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblCadastroPaciente)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lblAnotacoes)
                                .addGap(18, 18, 18)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 477, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lblTipo)
                                .addGap(18, 18, 18)
                                .addComponent(rdbtnAdulto)
                                .addGap(18, 18, 18)
                                .addComponent(rdbtnInfantil)))
                        .addContainerGap(78, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(rbtnDente38)
                                        .addGap(30, 30, 30)
                                        .addComponent(rbtnDente37))
                                    .addComponent(lblDente37))
                                .addGap(27, 27, 27)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblDente36)
                                    .addComponent(rbtnDente36))
                                .addGap(33, 33, 33)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblDente35)
                                    .addComponent(rbtnDente35))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(rbtnDente34, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblDente34, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addGap(26, 26, 26)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(rbtnDente33)
                                    .addComponent(lblDente33))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(rbtnDente32)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(rbtnDente31))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(lblDente32)
                                        .addGap(22, 22, 22)
                                        .addComponent(lblDente31)))
                                .addGap(248, 248, 248))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(6, 6, 6)
                                        .addComponent(lblDente38))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(335, 335, 335)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(rbtnDente41)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(rbtnDente42)
                                                .addGap(15, 15, 15)
                                                .addComponent(rbtnDente43))
                                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                                .addGap(7, 7, 7)
                                                .addComponent(lblDente41)
                                                .addGap(18, 18, 18)
                                                .addComponent(lblDente42)
                                                .addGap(18, 18, 18)
                                                .addComponent(lblDente43)))
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(lblDente44)
                                                .addGap(26, 26, 26)
                                                .addComponent(lblDente45))
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(rbtnDente44)
                                                .addGap(18, 18, 18)
                                                .addComponent(rbtnDente45)))
                                        .addGap(27, 27, 27)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(rbtnDente46)
                                            .addComponent(lblDente46))
                                        .addGap(34, 34, 34)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(rbtnDente47)
                                            .addComponent(lblDente47))
                                        .addGap(31, 31, 31)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lblDente48)
                                            .addComponent(rbtnDente48)))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(rbtnDente28)
                                            .addComponent(lblDente28))
                                        .addGap(30, 30, 30)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(rbtnDente27)
                                            .addComponent(lblDente27))
                                        .addGap(26, 26, 26)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(rbtnDente26)
                                            .addComponent(lblDente26))
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(rbtnDente25)
                                            .addComponent(lblDente25))
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(rbtnDente24)
                                            .addComponent(lblDente24))
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(rbtnDente23)
                                            .addComponent(lblDente23))
                                        .addGap(26, 26, 26)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(rbtnDente22)
                                            .addComponent(lblDente22))
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lblDente21)
                                            .addComponent(rbtnDente21))
                                        .addGap(34, 34, 34)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(rbtnDente11)
                                            .addComponent(lblDente11))
                                        .addGap(22, 22, 22)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(rbtnDente12)
                                            .addComponent(lblDente12))
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                                .addComponent(lblDente13)
                                                .addGap(32, 32, 32)
                                                .addComponent(lblDente14))
                                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                                .addComponent(rbtnDente13)
                                                .addGap(18, 18, 18)
                                                .addComponent(rbtnDente14)))
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(lblDente15)
                                            .addComponent(rbtnDente15))
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(rbtnDente16, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(lblDente16, javax.swing.GroupLayout.Alignment.TRAILING))
                                        .addGap(27, 27, 27)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(rbtnDente17)
                                            .addComponent(lblDente17))
                                        .addGap(29, 29, 29)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(lblDente18)
                                            .addComponent(rbtnDente18))))
                                .addGap(0, 0, Short.MAX_VALUE))))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(124, 124, 124)
                .addComponent(lblImagem2_1)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(btnSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(lblImagem2_2)
                        .addGap(127, 127, 127))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblDente75)
                                    .addComponent(rbtnDente75)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(rbtnDente65)
                                    .addComponent(lblDente65))
                                .addGap(25, 25, 25)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblDente64)
                                    .addComponent(rbtnDente64)
                                    .addComponent(rbtnDente74)
                                    .addComponent(lblDente74))
                                .addGap(31, 31, 31)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lblDente63)
                                            .addComponent(rbtnDente63))
                                        .addGap(26, 26, 26)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lblDente62)
                                            .addComponent(rbtnDente62)))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(rbtnDente73)
                                            .addComponent(lblDente73))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lblDente72)
                                            .addComponent(rbtnDente72))))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(lblDente61)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(lblDente51))
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(rbtnDente61)
                                                .addGap(34, 34, 34)
                                                .addComponent(rbtnDente51)))
                                        .addGap(26, 26, 26)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(rbtnDente52)
                                            .addComponent(lblDente52))
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(rbtnDente53)
                                            .addComponent(lblDente53))
                                        .addGap(29, 29, 29)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(rbtnDente54)
                                            .addComponent(lblDente54))
                                        .addGap(28, 28, 28)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(lblDente55)
                                            .addComponent(rbtnDente55)))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(rbtnDente71)
                                            .addComponent(lblDente71))
                                        .addGap(34, 34, 34)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(lblDente81)
                                            .addComponent(rbtnDente81))
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(rbtnDente82)
                                            .addComponent(lblDente82))
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(rbtnDente83)
                                            .addComponent(lblDente83))
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(rbtnDente84)
                                            .addComponent(lblDente84))
                                        .addGap(44, 44, 44)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(rbtnDente85)
                                            .addComponent(lblDente85))))))
                        .addGap(139, 139, 139))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblCadastroPaciente)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTipo)
                    .addComponent(rdbtnAdulto)
                    .addComponent(rdbtnInfantil))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblImagem1_1, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rbtnDente28)
                    .addComponent(rbtnDente27)
                    .addComponent(rbtnDente26)
                    .addComponent(rbtnDente24)
                    .addComponent(rbtnDente23)
                    .addComponent(rbtnDente22)
                    .addComponent(rbtnDente21)
                    .addComponent(rbtnDente11)
                    .addComponent(rbtnDente12)
                    .addComponent(rbtnDente13)
                    .addComponent(rbtnDente15)
                    .addComponent(rbtnDente16)
                    .addComponent(rbtnDente17)
                    .addComponent(rbtnDente18)
                    .addComponent(rbtnDente14)
                    .addComponent(rbtnDente25))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblDente16)
                    .addComponent(lblDente18)
                    .addComponent(lblDente21)
                    .addComponent(lblDente14)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblDente11)
                        .addComponent(lblDente12)
                        .addComponent(lblDente13)
                        .addComponent(lblDente15)
                        .addComponent(lblDente17))
                    .addComponent(lblDente28)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblDente22)
                        .addComponent(lblDente23)
                        .addComponent(lblDente24)
                        .addComponent(lblDente25)
                        .addComponent(lblDente26)
                        .addComponent(lblDente27)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 134, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblDente38)
                            .addComponent(lblDente36)
                            .addComponent(lblDente31)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(lblDente37)
                                .addComponent(lblDente32)
                                .addComponent(lblDente33)
                                .addComponent(lblDente34)
                                .addComponent(lblDente35)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(rbtnDente38, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(rbtnDente37, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(rbtnDente36, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(rbtnDente34, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(rbtnDente33, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(rbtnDente32, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(rbtnDente31, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(rbtnDente35, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lblDente47, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(lblDente48))
                            .addComponent(lblDente43)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(lblDente42)
                                .addComponent(lblDente41)
                                .addComponent(lblDente44)
                                .addComponent(lblDente45)
                                .addComponent(lblDente46)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(rbtnDente41, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(rbtnDente42, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(rbtnDente43, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(rbtnDente47, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(rbtnDente48, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(rbtnDente44, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(rbtnDente46, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(rbtnDente45, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addComponent(lblImagem1_2, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(54, 54, 54)
                .addComponent(lblImagem2_1, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(rbtnDente64)
                                .addComponent(rbtnDente62)
                                .addComponent(rbtnDente61)
                                .addComponent(rbtnDente65)
                                .addComponent(rbtnDente51)
                                .addComponent(rbtnDente52))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lblDente51)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblDente61)
                                    .addComponent(lblDente62))
                                .addComponent(lblDente64)
                                .addComponent(lblDente65)))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(rbtnDente63)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(lblDente63)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(rbtnDente54)
                            .addComponent(rbtnDente55, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblDente55)
                            .addComponent(lblDente54)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(rbtnDente53)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblDente53)
                            .addComponent(lblDente52))))
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblDente72)
                            .addComponent(lblDente71))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                        .addComponent(rbtnDente72))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblDente73)
                            .addComponent(lblDente74))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(rbtnDente73))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblDente81)
                                    .addComponent(lblDente82)
                                    .addComponent(lblDente83)
                                    .addComponent(lblDente84)
                                    .addComponent(lblDente85))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(rbtnDente81)
                                    .addComponent(rbtnDente82)
                                    .addComponent(rbtnDente83)
                                    .addComponent(rbtnDente84)
                                    .addComponent(rbtnDente85)))
                            .addComponent(rbtnDente71, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(lblDente75)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(rbtnDente75)
                            .addComponent(rbtnDente74))))
                .addGap(16, 16, 16)
                .addComponent(lblImagem2_2, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblAnotacoes))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void rbtnDente54ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtnDente54ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbtnDente54ActionPerformed

    private void rbtnDente63ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtnDente63ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbtnDente63ActionPerformed

    private void rbtnDente46ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtnDente46ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbtnDente46ActionPerformed

    private void rdbtnInfantilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdbtnInfantilActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rdbtnInfantilActionPerformed

    private void rdbtnInfantilStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_rdbtnInfantilStateChanged
        if (rdbtnInfantil.isSelected() == true) {
            lblImagem1_1.setVisible(false);
            lblImagem1_2.setVisible(false);
            lblImagem2_1.setVisible(true);
            lblImagem2_2.setVisible(true);

            lblDente51.setVisible(true);
            lblDente52.setVisible(true);
            lblDente53.setVisible(true);
            lblDente54.setVisible(true);
            lblDente55.setVisible(true);
            lblDente61.setVisible(true);
            lblDente62.setVisible(true);
            lblDente63.setVisible(true);
            lblDente64.setVisible(true);
            lblDente65.setVisible(true);
            lblDente71.setVisible(true);
            lblDente72.setVisible(true);
            lblDente73.setVisible(true);
            lblDente74.setVisible(true);
            lblDente75.setVisible(true);
            lblDente81.setVisible(true);
            lblDente82.setVisible(true);
            lblDente83.setVisible(true);
            lblDente84.setVisible(true);
            lblDente85.setVisible(true);

            rbtnDente51.setVisible(true);
            rbtnDente52.setVisible(true);
            rbtnDente53.setVisible(true);
            rbtnDente54.setVisible(true);
            rbtnDente55.setVisible(true);
            rbtnDente61.setVisible(true);
            rbtnDente62.setVisible(true);
            rbtnDente63.setVisible(true);
            rbtnDente64.setVisible(true);
            rbtnDente65.setVisible(true);
            rbtnDente71.setVisible(true);
            rbtnDente72.setVisible(true);
            rbtnDente73.setVisible(true);
            rbtnDente74.setVisible(true);
            rbtnDente75.setVisible(true);
            rbtnDente81.setVisible(true);
            rbtnDente82.setVisible(true);
            rbtnDente83.setVisible(true);
            rbtnDente84.setVisible(true);
            rbtnDente85.setVisible(true);

            lblDente11.setVisible(false);
            lblDente12.setVisible(false);
            lblDente13.setVisible(false);
            lblDente14.setVisible(false);
            lblDente15.setVisible(false);
            lblDente16.setVisible(false);
            lblDente17.setVisible(false);
            lblDente18.setVisible(false);
            lblDente21.setVisible(false);
            lblDente22.setVisible(false);
            lblDente23.setVisible(false);
            lblDente24.setVisible(false);
            lblDente25.setVisible(false);
            lblDente26.setVisible(false);
            lblDente27.setVisible(false);
            lblDente28.setVisible(false);
            lblDente31.setVisible(false);
            lblDente32.setVisible(false);
            lblDente33.setVisible(false);
            lblDente34.setVisible(false);
            lblDente35.setVisible(false);
            lblDente36.setVisible(false);
            lblDente37.setVisible(false);
            lblDente38.setVisible(false);
            lblDente41.setVisible(false);
            lblDente42.setVisible(false);
            lblDente43.setVisible(false);
            lblDente44.setVisible(false);
            lblDente45.setVisible(false);
            lblDente46.setVisible(false);
            lblDente47.setVisible(false);
            lblDente48.setVisible(false);

            rbtnDente11.setVisible(false);
            rbtnDente11.setSelected(false);
            rbtnDente12.setVisible(false);
            rbtnDente12.setSelected(false);
            rbtnDente13.setVisible(false);
            rbtnDente13.setSelected(false);
            rbtnDente14.setVisible(false);
            rbtnDente14.setSelected(false);
            rbtnDente15.setVisible(false);
            rbtnDente15.setSelected(false);
            rbtnDente16.setVisible(false);
            rbtnDente16.setSelected(false);
            rbtnDente17.setVisible(false);
            rbtnDente17.setSelected(false);
            rbtnDente18.setVisible(false);
            rbtnDente18.setSelected(false);
            rbtnDente21.setVisible(false);
            rbtnDente21.setSelected(false);
            rbtnDente22.setVisible(false);
            rbtnDente22.setSelected(false);
            rbtnDente23.setVisible(false);
            rbtnDente23.setSelected(false);
            rbtnDente24.setVisible(false);
            rbtnDente24.setSelected(false);
            rbtnDente25.setVisible(false);
            rbtnDente25.setSelected(false);
            rbtnDente26.setVisible(false);
            rbtnDente26.setSelected(false);
            rbtnDente27.setVisible(false);
            rbtnDente27.setSelected(false);
            rbtnDente28.setVisible(false);
            rbtnDente28.setSelected(false);
            rbtnDente31.setVisible(false);
            rbtnDente31.setSelected(false);
            rbtnDente32.setVisible(false);
            rbtnDente32.setSelected(false);
            rbtnDente33.setVisible(false);
            rbtnDente33.setSelected(false);
            rbtnDente34.setVisible(false);
            rbtnDente34.setSelected(false);
            rbtnDente35.setVisible(false);
            rbtnDente35.setSelected(false);
            rbtnDente36.setVisible(false);
            rbtnDente36.setSelected(false);
            rbtnDente37.setVisible(false);
            rbtnDente37.setSelected(false);
            rbtnDente38.setVisible(false);
            rbtnDente38.setSelected(false);
            rbtnDente41.setVisible(false);
            rbtnDente41.setSelected(false);
            rbtnDente42.setVisible(false);
            rbtnDente42.setSelected(false);
            rbtnDente43.setVisible(false);
            rbtnDente43.setSelected(false);
            rbtnDente44.setVisible(false);
            rbtnDente44.setSelected(false);
            rbtnDente45.setVisible(false);
            rbtnDente45.setSelected(false);
            rbtnDente46.setVisible(false);
            rbtnDente46.setSelected(false);
            rbtnDente47.setVisible(false);
            rbtnDente47.setSelected(false);
            rbtnDente48.setVisible(false);
            rbtnDente48.setSelected(false);
        }
    }//GEN-LAST:event_rdbtnInfantilStateChanged

    private void rdbtnAdultoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdbtnAdultoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rdbtnAdultoActionPerformed

    private void rdbtnAdultoStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_rdbtnAdultoStateChanged
        if (rdbtnAdulto.isSelected() == true) {
            lblImagem1_1.setVisible(true);
            lblImagem1_2.setVisible(true);
            lblImagem2_1.setVisible(false);
            lblImagem2_2.setVisible(false);

            lblDente11.setVisible(true);
            lblDente12.setVisible(true);
            lblDente13.setVisible(true);
            lblDente14.setVisible(true);
            lblDente15.setVisible(true);
            lblDente16.setVisible(true);
            lblDente17.setVisible(true);
            lblDente18.setVisible(true);
            lblDente21.setVisible(true);
            lblDente22.setVisible(true);
            lblDente23.setVisible(true);
            lblDente24.setVisible(true);
            lblDente25.setVisible(true);
            lblDente26.setVisible(true);
            lblDente27.setVisible(true);
            lblDente28.setVisible(true);
            lblDente31.setVisible(true);
            lblDente32.setVisible(true);
            lblDente33.setVisible(true);
            lblDente34.setVisible(true);
            lblDente35.setVisible(true);
            lblDente36.setVisible(true);
            lblDente37.setVisible(true);
            lblDente38.setVisible(true);
            lblDente41.setVisible(true);
            lblDente42.setVisible(true);
            lblDente43.setVisible(true);
            lblDente44.setVisible(true);
            lblDente45.setVisible(true);
            lblDente46.setVisible(true);
            lblDente47.setVisible(true);
            lblDente48.setVisible(true);

            rbtnDente11.setVisible(true);
            rbtnDente12.setVisible(true);
            rbtnDente13.setVisible(true);
            rbtnDente14.setVisible(true);
            rbtnDente15.setVisible(true);
            rbtnDente16.setVisible(true);
            rbtnDente17.setVisible(true);
            rbtnDente18.setVisible(true);
            rbtnDente21.setVisible(true);
            rbtnDente22.setVisible(true);
            rbtnDente23.setVisible(true);
            rbtnDente24.setVisible(true);
            rbtnDente25.setVisible(true);
            rbtnDente26.setVisible(true);
            rbtnDente27.setVisible(true);
            rbtnDente28.setVisible(true);
            rbtnDente31.setVisible(true);
            rbtnDente32.setVisible(true);
            rbtnDente33.setVisible(true);
            rbtnDente34.setVisible(true);
            rbtnDente35.setVisible(true);
            rbtnDente36.setVisible(true);
            rbtnDente37.setVisible(true);
            rbtnDente38.setVisible(true);
            rbtnDente41.setVisible(true);
            rbtnDente42.setVisible(true);
            rbtnDente43.setVisible(true);
            rbtnDente44.setVisible(true);
            rbtnDente45.setVisible(true);
            rbtnDente46.setVisible(true);
            rbtnDente47.setVisible(true);
            rbtnDente48.setVisible(true);

            lblDente51.setVisible(false);
            lblDente52.setVisible(false);
            lblDente53.setVisible(false);
            lblDente54.setVisible(false);
            lblDente55.setVisible(false);
            lblDente61.setVisible(false);
            lblDente62.setVisible(false);
            lblDente63.setVisible(false);
            lblDente64.setVisible(false);
            lblDente65.setVisible(false);
            lblDente71.setVisible(false);
            lblDente72.setVisible(false);
            lblDente73.setVisible(false);
            lblDente74.setVisible(false);
            lblDente75.setVisible(false);
            lblDente81.setVisible(false);
            lblDente82.setVisible(false);
            lblDente83.setVisible(false);
            lblDente84.setVisible(false);
            lblDente85.setVisible(false);

            rbtnDente51.setVisible(false);
            rbtnDente51.setSelected(false);
            rbtnDente52.setVisible(false);
            rbtnDente52.setSelected(false);
            rbtnDente53.setVisible(false);
            rbtnDente53.setSelected(false);
            rbtnDente54.setVisible(false);
            rbtnDente54.setSelected(false);
            rbtnDente55.setVisible(false);
            rbtnDente55.setSelected(false);
            rbtnDente61.setVisible(false);
            rbtnDente61.setSelected(false);
            rbtnDente62.setVisible(false);
            rbtnDente62.setSelected(false);
            rbtnDente63.setVisible(false);
            rbtnDente63.setSelected(false);
            rbtnDente64.setVisible(false);
            rbtnDente64.setSelected(false);
            rbtnDente65.setVisible(false);
            rbtnDente65.setSelected(false);
            rbtnDente71.setVisible(false);
            rbtnDente71.setSelected(false);
            rbtnDente72.setVisible(false);
            rbtnDente72.setSelected(false);
            rbtnDente73.setVisible(false);
            rbtnDente73.setSelected(false);
            rbtnDente74.setVisible(false);
            rbtnDente74.setSelected(false);
            rbtnDente75.setVisible(false);
            rbtnDente75.setSelected(false);
            rbtnDente81.setVisible(false);
            rbtnDente81.setSelected(false);
            rbtnDente82.setVisible(false);
            rbtnDente82.setSelected(false);
            rbtnDente83.setVisible(false);
            rbtnDente83.setSelected(false);
            rbtnDente84.setVisible(false);
            rbtnDente84.setSelected(false);
            rbtnDente85.setVisible(false);
            rbtnDente85.setSelected(false);
        }
    }//GEN-LAST:event_rdbtnAdultoStateChanged

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        dispose();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void rbtnDente55ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtnDente55ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbtnDente55ActionPerformed

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
        cadastraOdontograma();
    }//GEN-LAST:event_btnSalvarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroOdontograma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroOdontograma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroOdontograma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroOdontograma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaCadastroOdontograma().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnSalvar;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblAnotacoes;
    private javax.swing.JLabel lblCadastroPaciente;
    private javax.swing.JLabel lblDente11;
    private javax.swing.JLabel lblDente12;
    private javax.swing.JLabel lblDente13;
    private javax.swing.JLabel lblDente14;
    private javax.swing.JLabel lblDente15;
    private javax.swing.JLabel lblDente16;
    private javax.swing.JLabel lblDente17;
    private javax.swing.JLabel lblDente18;
    private javax.swing.JLabel lblDente21;
    private javax.swing.JLabel lblDente22;
    private javax.swing.JLabel lblDente23;
    private javax.swing.JLabel lblDente24;
    private javax.swing.JLabel lblDente25;
    private javax.swing.JLabel lblDente26;
    private javax.swing.JLabel lblDente27;
    private javax.swing.JLabel lblDente28;
    private javax.swing.JLabel lblDente31;
    private javax.swing.JLabel lblDente32;
    private javax.swing.JLabel lblDente33;
    private javax.swing.JLabel lblDente34;
    private javax.swing.JLabel lblDente35;
    private javax.swing.JLabel lblDente36;
    private javax.swing.JLabel lblDente37;
    private javax.swing.JLabel lblDente38;
    private javax.swing.JLabel lblDente41;
    private javax.swing.JLabel lblDente42;
    private javax.swing.JLabel lblDente43;
    private javax.swing.JLabel lblDente44;
    private javax.swing.JLabel lblDente45;
    private javax.swing.JLabel lblDente46;
    private javax.swing.JLabel lblDente47;
    private javax.swing.JLabel lblDente48;
    private javax.swing.JLabel lblDente51;
    private javax.swing.JLabel lblDente52;
    private javax.swing.JLabel lblDente53;
    private javax.swing.JLabel lblDente54;
    private javax.swing.JLabel lblDente55;
    private javax.swing.JLabel lblDente61;
    private javax.swing.JLabel lblDente62;
    private javax.swing.JLabel lblDente63;
    private javax.swing.JLabel lblDente64;
    private javax.swing.JLabel lblDente65;
    private javax.swing.JLabel lblDente71;
    private javax.swing.JLabel lblDente72;
    private javax.swing.JLabel lblDente73;
    private javax.swing.JLabel lblDente74;
    private javax.swing.JLabel lblDente75;
    private javax.swing.JLabel lblDente81;
    private javax.swing.JLabel lblDente82;
    private javax.swing.JLabel lblDente83;
    private javax.swing.JLabel lblDente84;
    private javax.swing.JLabel lblDente85;
    private javax.swing.JLabel lblImagem1_1;
    private javax.swing.JLabel lblImagem1_2;
    private javax.swing.JLabel lblImagem2_1;
    private javax.swing.JLabel lblImagem2_2;
    private javax.swing.JLabel lblTipo;
    private javax.swing.JRadioButton rbtnDente11;
    private javax.swing.JRadioButton rbtnDente12;
    private javax.swing.JRadioButton rbtnDente13;
    private javax.swing.JRadioButton rbtnDente14;
    private javax.swing.JRadioButton rbtnDente15;
    private javax.swing.JRadioButton rbtnDente16;
    private javax.swing.JRadioButton rbtnDente17;
    private javax.swing.JRadioButton rbtnDente18;
    private javax.swing.JRadioButton rbtnDente21;
    private javax.swing.JRadioButton rbtnDente22;
    private javax.swing.JRadioButton rbtnDente23;
    private javax.swing.JRadioButton rbtnDente24;
    private javax.swing.JRadioButton rbtnDente25;
    private javax.swing.JRadioButton rbtnDente26;
    private javax.swing.JRadioButton rbtnDente27;
    private javax.swing.JRadioButton rbtnDente28;
    private javax.swing.JRadioButton rbtnDente31;
    private javax.swing.JRadioButton rbtnDente32;
    private javax.swing.JRadioButton rbtnDente33;
    private javax.swing.JRadioButton rbtnDente34;
    private javax.swing.JRadioButton rbtnDente35;
    private javax.swing.JRadioButton rbtnDente36;
    private javax.swing.JRadioButton rbtnDente37;
    private javax.swing.JRadioButton rbtnDente38;
    private javax.swing.JRadioButton rbtnDente41;
    private javax.swing.JRadioButton rbtnDente42;
    private javax.swing.JRadioButton rbtnDente43;
    private javax.swing.JRadioButton rbtnDente44;
    private javax.swing.JRadioButton rbtnDente45;
    private javax.swing.JRadioButton rbtnDente46;
    private javax.swing.JRadioButton rbtnDente47;
    private javax.swing.JRadioButton rbtnDente48;
    private javax.swing.JRadioButton rbtnDente51;
    private javax.swing.JRadioButton rbtnDente52;
    private javax.swing.JRadioButton rbtnDente53;
    private javax.swing.JRadioButton rbtnDente54;
    private javax.swing.JRadioButton rbtnDente55;
    private javax.swing.JRadioButton rbtnDente61;
    private javax.swing.JRadioButton rbtnDente62;
    private javax.swing.JRadioButton rbtnDente63;
    private javax.swing.JRadioButton rbtnDente64;
    private javax.swing.JRadioButton rbtnDente65;
    private javax.swing.JRadioButton rbtnDente71;
    private javax.swing.JRadioButton rbtnDente72;
    private javax.swing.JRadioButton rbtnDente73;
    private javax.swing.JRadioButton rbtnDente74;
    private javax.swing.JRadioButton rbtnDente75;
    private javax.swing.JRadioButton rbtnDente81;
    private javax.swing.JRadioButton rbtnDente82;
    private javax.swing.JRadioButton rbtnDente83;
    private javax.swing.JRadioButton rbtnDente84;
    private javax.swing.JRadioButton rbtnDente85;
    private javax.swing.JRadioButton rdbtnAdulto;
    private javax.swing.JRadioButton rdbtnInfantil;
    private javax.swing.JTextArea txtAnotacoes;
    // End of variables declaration//GEN-END:variables

    /**
     * Gera atalho de teclas para determinados comandos
     */
    public void geraAcessibilidade() {
        btnSalvar.setMnemonic(KeyEvent.VK_S);
        btnCancelar.setMnemonic(KeyEvent.VK_C);
    }

    /**
     * Realiza o cadastro de odontograma, integrando os métodos da classe
     * OdontogramaDAO
     */
    public void cadastraOdontograma() {
        Odontograma odontograma = new Odontograma();
        OdontogramaDAO odonDao = new OdontogramaDAO();
        PacienteDAO pacDao = new PacienteDAO();
        boolean status;
        int resposta;

        odontograma.setAnotacoes(txtAnotacoes.getText());
        if (rdbtnAdulto.isSelected() == true) {
            odontograma.setTipo('A');
        } else if (rdbtnInfantil.isSelected() == true) {
            odontograma.setTipo('I');
        }
        odontograma.setPaciente(pacDao.retornaPaciente(telaPrincipal.retornaIdPacienteSelecionado()));

        status = odonDao.conectar();
        if (status == false) {
            JOptionPane.showMessageDialog(null, "Erro de conexão.");
        } else {
            int idPaciente = odontograma.getPaciente().getId();
            int idOdontograma = odonDao.retornaIDOdontograma(idPaciente);
            
            odonDao.excluirRelacaoOdontoDenteAntiga(idOdontograma);
            odonDao.excluirOdontogramaAntigo(idPaciente);
            
            resposta = odonDao.salvar(odontograma);
            switch (resposta) {
                case 1:

                    int i = 0,
                     j = 1;
                    DenteDAO denDao = new DenteDAO();
                    denDao.conectar();
                    Dente[] dentesOdontograma = new Dente[32];
                    if (rdbtnAdulto.isSelected() == true) {
                        if (rbtnDente11.isSelected() == true) {
                            dentesOdontograma[i] = denDao.retornaDente(j);
                            i++;
                        }
                        j++;
                        if (rbtnDente12.isSelected() == true) {
                            dentesOdontograma[i] = denDao.retornaDente(j);
                            i++;
                        }
                        j++;
                        if (rbtnDente13.isSelected() == true) {
                            dentesOdontograma[i] = denDao.retornaDente(j);
                            i++;
                        }
                        j++;
                        if (rbtnDente14.isSelected() == true) {
                            dentesOdontograma[i] = denDao.retornaDente(j);
                            i++;
                        }
                        j++;
                        if (rbtnDente15.isSelected() == true) {
                            dentesOdontograma[i] = denDao.retornaDente(j);
                            i++;
                        }
                        j++;
                        if (rbtnDente16.isSelected() == true) {
                            dentesOdontograma[i] = denDao.retornaDente(j);
                            i++;
                        }
                        j++;
                        if (rbtnDente17.isSelected() == true) {
                            dentesOdontograma[i] = denDao.retornaDente(j);
                            i++;
                        }
                        j++;
                        if (rbtnDente18.isSelected() == true) {
                            dentesOdontograma[i] = denDao.retornaDente(j);
                            i++;
                        }
                        j++;
                        if (rbtnDente21.isSelected() == true) {
                            dentesOdontograma[i] = denDao.retornaDente(j);
                            i++;
                        }
                        j++;
                        if (rbtnDente22.isSelected() == true) {
                            dentesOdontograma[i] = denDao.retornaDente(j);
                            i++;
                        }
                        j++;
                        if (rbtnDente23.isSelected() == true) {
                            dentesOdontograma[i] = denDao.retornaDente(j);
                            i++;
                        }
                        j++;
                        if (rbtnDente24.isSelected() == true) {
                            dentesOdontograma[i] = denDao.retornaDente(j);
                            i++;
                        }
                        j++;
                        if (rbtnDente25.isSelected() == true) {
                            dentesOdontograma[i] = denDao.retornaDente(j);
                            i++;
                        }
                        j++;
                        if (rbtnDente26.isSelected() == true) {
                            dentesOdontograma[i] = denDao.retornaDente(j);
                            i++;
                        }
                        j++;
                        if (rbtnDente27.isSelected() == true) {
                            dentesOdontograma[i] = denDao.retornaDente(j);
                            i++;
                        }
                        j++;
                        if (rbtnDente28.isSelected() == true) {
                            dentesOdontograma[i] = denDao.retornaDente(j);
                            i++;
                        }
                        j++;
                        if (rbtnDente31.isSelected() == true) {
                            dentesOdontograma[i] = denDao.retornaDente(j);
                            i++;
                        }
                        j++;
                        if (rbtnDente32.isSelected() == true) {
                            dentesOdontograma[i] = denDao.retornaDente(j);
                            i++;
                        }
                        j++;
                        if (rbtnDente33.isSelected() == true) {
                            dentesOdontograma[i] = denDao.retornaDente(j);
                            i++;
                        }
                        j++;
                        if (rbtnDente34.isSelected() == true) {
                            dentesOdontograma[i] = denDao.retornaDente(j);
                            i++;
                        }
                        j++;
                        if (rbtnDente35.isSelected() == true) {
                            dentesOdontograma[i] = denDao.retornaDente(j);
                            i++;
                        }
                        j++;
                        if (rbtnDente36.isSelected() == true) {
                            dentesOdontograma[i] = denDao.retornaDente(j);
                            i++;
                        }
                        j++;
                        if (rbtnDente37.isSelected() == true) {
                            dentesOdontograma[i] = denDao.retornaDente(j);
                            i++;
                        }
                        j++;
                        if (rbtnDente38.isSelected() == true) {
                            dentesOdontograma[i] = denDao.retornaDente(j);
                            i++;
                        }
                        j++;
                        if (rbtnDente41.isSelected() == true) {
                            dentesOdontograma[i] = denDao.retornaDente(j);
                            i++;
                        }
                        j++;
                        if (rbtnDente42.isSelected() == true) {
                            dentesOdontograma[i] = denDao.retornaDente(j);
                            i++;
                        }
                        j++;
                        if (rbtnDente43.isSelected() == true) {
                            dentesOdontograma[i] = denDao.retornaDente(j);
                            i++;
                        }
                        j++;
                        if (rbtnDente44.isSelected() == true) {
                            dentesOdontograma[i] = denDao.retornaDente(j);
                            i++;
                        }
                        j++;
                        if (rbtnDente45.isSelected() == true) {
                            dentesOdontograma[i] = denDao.retornaDente(j);
                            i++;
                        }
                        j++;
                        if (rbtnDente46.isSelected() == true) {
                            dentesOdontograma[i] = denDao.retornaDente(j);
                            i++;
                        }
                        j++;
                        if (rbtnDente47.isSelected() == true) {
                            dentesOdontograma[i] = denDao.retornaDente(j);
                            i++;
                        }
                        j++;
                        if (rbtnDente48.isSelected() == true) {
                            dentesOdontograma[i] = denDao.retornaDente(j);
                            i++;
                        }

                    } else if (rdbtnInfantil.isSelected() == true) {
                        j = 33;
                        if (rbtnDente51.isSelected() == true) {
                            dentesOdontograma[i] = denDao.retornaDente(j);
                            i++;
                        }
                        j++;
                        if (rbtnDente52.isSelected() == true) {
                            dentesOdontograma[i] = denDao.retornaDente(j);
                            i++;
                        }
                        j++;
                        if (rbtnDente53.isSelected() == true) {
                            dentesOdontograma[i] = denDao.retornaDente(j);
                            i++;
                        }
                        j++;
                        if (rbtnDente54.isSelected() == true) {
                            dentesOdontograma[i] = denDao.retornaDente(j);
                            i++;
                        }
                        j++;
                        if (rbtnDente55.isSelected() == true) {
                            dentesOdontograma[i] = denDao.retornaDente(j);
                            i++;
                        }
                        j++;
                        if (rbtnDente61.isSelected() == true) {
                            dentesOdontograma[i] = denDao.retornaDente(j);
                            i++;
                        }
                        j++;
                        if (rbtnDente62.isSelected() == true) {
                            dentesOdontograma[i] = denDao.retornaDente(j);
                            i++;
                        }
                        j++;
                        if (rbtnDente63.isSelected() == true) {
                            dentesOdontograma[i] = denDao.retornaDente(j);
                            i++;
                        }
                        j++;
                        if (rbtnDente64.isSelected() == true) {
                            dentesOdontograma[i] = denDao.retornaDente(j);
                            i++;
                        }
                        j++;
                        if (rbtnDente65.isSelected() == true) {
                            dentesOdontograma[i] = denDao.retornaDente(j);
                            i++;
                        }
                        j++;
                        if (rbtnDente71.isSelected() == true) {
                            dentesOdontograma[i] = denDao.retornaDente(j);
                            i++;
                        }
                        j++;
                        if (rbtnDente72.isSelected() == true) {
                            dentesOdontograma[i] = denDao.retornaDente(j);
                            i++;
                        }
                        j++;
                        if (rbtnDente73.isSelected() == true) {
                            dentesOdontograma[i] = denDao.retornaDente(j);
                            i++;
                        }
                        j++;
                        if (rbtnDente74.isSelected() == true) {
                            dentesOdontograma[i] = denDao.retornaDente(j);
                            i++;
                        }
                        j++;
                        if (rbtnDente75.isSelected() == true) {
                            dentesOdontograma[i] = denDao.retornaDente(j);
                            i++;
                        }
                        j++;
                        if (rbtnDente81.isSelected() == true) {
                            dentesOdontograma[i] = denDao.retornaDente(j);
                            i++;
                        }
                        j++;
                        if (rbtnDente82.isSelected() == true) {
                            dentesOdontograma[i] = denDao.retornaDente(j);
                            i++;
                        }
                        j++;
                        if (rbtnDente83.isSelected() == true) {
                            dentesOdontograma[i] = denDao.retornaDente(j);
                            i++;
                        }
                        j++;
                        if (rbtnDente84.isSelected() == true) {
                            dentesOdontograma[i] = denDao.retornaDente(j);
                            i++;
                        }
                        j++;
                        if (rbtnDente85.isSelected() == true) {
                            dentesOdontograma[i] = denDao.retornaDente(j);
                            i++;
                        }

                    }
                    denDao.desconectar();

                    odontograma.setDentes(dentesOdontograma);
                    for (Dente dente : odontograma.getDentes()) {
                        if (dente != null) {
                            odonDao.salvarDentesOdontograma(odonDao.retornaIDOdontograma(odontograma.getPaciente().getId()), dente.getId());
                        }
                    }
                    odonDao.desconectar();
                    pacDao.desconectar();
                    JOptionPane.showMessageDialog(null, "Odontograma salvo com sucesso.");
                    dispose();
                    break;
                default:
                    JOptionPane.showMessageDialog(null, "Erro ao tentar salvar dado.");
                    break;
            }
        }
    }

    public void insereOdontogramaDoPaciente() {
        Odontograma odontograma = new Odontograma();
        OdontogramaDAO odonDao = new OdontogramaDAO();
        DenteDAO denDao = new DenteDAO();
        boolean status;
        int resposta;

        status = odonDao.conectar();
        if (status == false) {
            JOptionPane.showMessageDialog(null, "Erro de conexão.");
        } else {
            odontograma = odonDao.retornaOdontograma(telaPrincipal.retornaIdPacienteSelecionado());
            if (odontograma.getTipo() == 'A') {
                rdbtnAdulto.setSelected(true);
                rdbtnAdulto.setEnabled(false);
                rdbtnInfantil.setEnabled(false);
            } else if (odontograma.getTipo() == 'I') {
                rdbtnInfantil.setSelected(true);
                rdbtnInfantil.setEnabled(false);
                rdbtnAdulto.setEnabled(false);
            }
            txtAnotacoes.setText(odontograma.getAnotacoes());

            status = denDao.conectar();
            if (status == false) {
                JOptionPane.showMessageDialog(null, "Erro de conexão.");
            } else {
                List<Integer> listaIdDentes = denDao.retornaIDsDentes(odontograma.getId());
                for (int idDente : listaIdDentes) {
                    if (odontograma.getTipo() == 'A') {
                        if (idDente == 1) {
                            rbtnDente11.setSelected(true);
                        }
                        if (idDente == 2) {
                            rbtnDente12.setSelected(true);
                        }
                        if (idDente == 3) {
                            rbtnDente13.setSelected(true);
                        }
                        if (idDente == 4) {
                            rbtnDente14.setSelected(true);
                        }
                        if (idDente == 5) {
                            rbtnDente15.setSelected(true);
                        }
                        if (idDente == 6) {
                            rbtnDente16.setSelected(true);
                        }
                        if (idDente == 7) {
                            rbtnDente17.setSelected(true);
                        }
                        if (idDente == 8) {
                            rbtnDente18.setSelected(true);
                        }
                        if (idDente == 9) {
                            rbtnDente21.setSelected(true);
                        }
                        if (idDente == 10) {
                            rbtnDente22.setSelected(true);
                        }
                        if (idDente == 11) {
                            rbtnDente23.setSelected(true);
                        }
                        if (idDente == 12) {
                            rbtnDente24.setSelected(true);
                        }
                        if (idDente == 13) {
                            rbtnDente25.setSelected(true);
                        }
                        if (idDente == 14) {
                            rbtnDente26.setSelected(true);
                        }
                        if (idDente == 15) {
                            rbtnDente27.setSelected(true);
                        }
                        if (idDente == 16) {
                            rbtnDente28.setSelected(true);
                        }
                        if (idDente == 17) {
                            rbtnDente31.setSelected(true);
                        }
                        if (idDente == 18) {
                            rbtnDente32.setSelected(true);
                        }
                        if (idDente == 19) {
                            rbtnDente33.setSelected(true);
                        }
                        if (idDente == 20) {
                            rbtnDente34.setSelected(true);
                        }
                        if (idDente == 21) {
                            rbtnDente35.setSelected(true);
                        }
                        if (idDente == 22) {
                            rbtnDente36.setSelected(true);
                        }
                        if (idDente == 23) {
                            rbtnDente37.setSelected(true);
                        }
                        if (idDente == 24) {
                            rbtnDente38.setSelected(true);
                        }
                        if (idDente == 25) {
                            rbtnDente41.setSelected(true);
                        }
                        if (idDente == 26) {
                            rbtnDente42.setSelected(true);
                        }
                        if (idDente == 27) {
                            rbtnDente43.setSelected(true);
                        }
                        if (idDente == 28) {
                            rbtnDente44.setSelected(true);
                        }
                        if (idDente == 29) {
                            rbtnDente45.setSelected(true);
                        }
                        if (idDente == 30) {
                            rbtnDente46.setSelected(true);
                        }
                        if (idDente == 31) {
                            rbtnDente47.setSelected(true);
                        }
                        if (idDente == 32) {
                            rbtnDente48.setSelected(true);
                        }

                    } else if (odontograma.getTipo() == 'I') {
                        if (idDente == 33) {
                            rbtnDente51.setSelected(true);
                        }
                        if (idDente == 34) {
                            rbtnDente52.setSelected(true);
                        }
                        if (idDente == 35) {
                            rbtnDente53.setSelected(true);
                        }
                        if (idDente == 36) {
                            rbtnDente54.setSelected(true);
                        }
                        if (idDente == 37) {
                            rbtnDente55.setSelected(true);
                        }
                        if (idDente == 38) {
                            rbtnDente61.setSelected(true);
                        }
                        if (idDente == 39) {
                            rbtnDente62.setSelected(true);
                        }
                        if (idDente == 40) {
                            rbtnDente63.setSelected(true);
                        }
                        if (idDente == 41) {
                            rbtnDente64.setSelected(true);
                        }
                        if (idDente == 42) {
                            rbtnDente65.setSelected(true);
                        }
                        if (idDente == 43) {
                            rbtnDente71.setSelected(true);
                        }
                        if (idDente == 44) {
                            rbtnDente72.setSelected(true);
                        }
                        if (idDente == 45) {
                            rbtnDente73.setSelected(true);
                        }
                        if (idDente == 46) {
                            rbtnDente74.setSelected(true);
                        }
                        if (idDente == 47) {
                            rbtnDente75.setSelected(true);
                        }
                        if (idDente == 48) {
                            rbtnDente81.setSelected(true);
                        }
                        if (idDente == 49) {
                            rbtnDente82.setSelected(true);
                        }
                        if (idDente == 50) {
                            rbtnDente83.setSelected(true);
                        }
                        if (idDente == 51) {
                            rbtnDente84.setSelected(true);
                        }
                        if (idDente == 52) {
                            rbtnDente85.setSelected(true);
                        }
                    }
                }
            }
            odonDao.desconectar();
            denDao.desconectar();
        }
    }
}
