package telas;

import classes.Atendimento;
import classes.AtendimentoDAO;
import classes.Receita;
import classes.ReceitaDAO;
import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;

/**
 * Tela para efetuar cadastros de receitas.
 */
public class TelaCadastroReceita extends javax.swing.JFrame {

    private TelaPrincipal telaPrincipal;

    public void MostraTela(TelaPrincipal obj) {
        this.telaPrincipal = obj;
        setVisible(true);
    }

    public TelaCadastroReceita() {
        initComponents();
        geraAcessibilidade();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        lblCadastroReceita = new javax.swing.JLabel();
        btnCadastrar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        lblMedicamento = new javax.swing.JLabel();
        lblQuantidade = new javax.swing.JLabel();
        txtQuantidade = new javax.swing.JTextField();
        lblInstrucoes = new javax.swing.JLabel();
        txtMedicamento = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtInstrucoes = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("SICODON");

        jPanel1.setBackground(new java.awt.Color(239, 235, 235));

        lblCadastroReceita.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblCadastroReceita.setText("Cadastro de Receita");

        btnCadastrar.setBackground(new java.awt.Color(30, 48, 112));
        btnCadastrar.setFont(new java.awt.Font("Segoe UI", 0, 35)); // NOI18N
        btnCadastrar.setForeground(new java.awt.Color(255, 255, 255));
        btnCadastrar.setText("Cadastrar");
        btnCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastrarActionPerformed(evt);
            }
        });

        btnCancelar.setBackground(new java.awt.Color(30, 48, 112));
        btnCancelar.setFont(new java.awt.Font("Segoe UI", 0, 35)); // NOI18N
        btnCancelar.setForeground(new java.awt.Color(255, 255, 255));
        btnCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/xis_.png"))); // NOI18N
        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        lblMedicamento.setFont(new java.awt.Font("Segoe UI", 0, 26)); // NOI18N
        lblMedicamento.setText("Medicamento:");

        lblQuantidade.setFont(new java.awt.Font("Segoe UI", 0, 26)); // NOI18N
        lblQuantidade.setText("Quantidade:");

        txtQuantidade.setBackground(new java.awt.Color(199, 199, 199));
        txtQuantidade.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N

        lblInstrucoes.setFont(new java.awt.Font("Segoe UI", 0, 26)); // NOI18N
        lblInstrucoes.setText("Instruções:");

        txtMedicamento.setBackground(new java.awt.Color(199, 199, 199));
        txtMedicamento.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N

        txtInstrucoes.setBackground(new java.awt.Color(199, 199, 199));
        txtInstrucoes.setColumns(20);
        txtInstrucoes.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        txtInstrucoes.setRows(5);
        jScrollPane2.setViewportView(txtInstrucoes);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnCadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblCadastroReceita)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(lblMedicamento)
                                            .addGap(36, 36, 36))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                            .addComponent(lblQuantidade)
                                            .addGap(59, 59, 59)))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(lblInstrucoes)
                                        .addGap(71, 71, 71)))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(txtQuantidade, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addComponent(jScrollPane2)
                                    .addComponent(txtMedicamento))))))
                .addGap(24, 24, 24))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(lblCadastroReceita)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblMedicamento)
                    .addComponent(txtMedicamento, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblQuantidade)
                    .addComponent(txtQuantidade, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(lblInstrucoes))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 18, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        dispose();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrarActionPerformed
        cadastraReceita();
    }//GEN-LAST:event_btnCadastrarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroReceita.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroReceita.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroReceita.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroReceita.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaCadastroReceita().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCadastrar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblCadastroReceita;
    private javax.swing.JLabel lblInstrucoes;
    private javax.swing.JLabel lblMedicamento;
    private javax.swing.JLabel lblQuantidade;
    private javax.swing.JTextArea txtInstrucoes;
    private javax.swing.JTextField txtMedicamento;
    private javax.swing.JTextField txtQuantidade;
    // End of variables declaration//GEN-END:variables

    /**
     * Realiza o cadastro de receita, integrando o método 'conectar' da classe
     * ReceitaDAO
     */
    public void cadastraReceita() {
        try {
            if (txtMedicamento.getText().isEmpty() || txtQuantidade.getText().isEmpty() || txtInstrucoes.getText().isEmpty()) {
                JOptionPane.showMessageDialog(null, "Todos os campos precisam ser preenchidos.");
            } else {
                Receita receita = new Receita();
                Atendimento atendimento = new Atendimento();
                ReceitaDAO recDao = new ReceitaDAO();
                AtendimentoDAO atenDao = new AtendimentoDAO();
                boolean status;
                int resposta;

                receita.setMedicamento(txtMedicamento.getText());
                receita.setQuantidade(Integer.parseInt(txtQuantidade.getText()));
                receita.setInstrucoes(txtInstrucoes.getText());

                status = atenDao.conectar();
                if (status == false) {
                    JOptionPane.showMessageDialog(null, "Erro de conexão.");
                } else {
                    atendimento = atenDao.retornaAtendimento(telaPrincipal.retornaIdAtendimentoSelecionado());
                }
                atenDao.desconectar();
                receita.setAtendimento(atendimento);

                status = recDao.conectar();
                if (status == false) {
                    JOptionPane.showMessageDialog(null, "Erro de conexão.");
                } else {
                    resposta = recDao.salvar(receita);
                    switch (resposta) {
                        case 1:
                            JOptionPane.showMessageDialog(null, "Cadastro de receita efetuado com sucesso.");
                            break;
                        case 1062:
                            JOptionPane.showMessageDialog(null, "Receita já foi cadastrado.");
                            break;
                        default:
                            JOptionPane.showMessageDialog(null, "Erro ao tentar salvar dado.");
                            break;
                    }
                }
                recDao.desconectar();
                dispose();
            }
        } catch (IllegalArgumentException exc) {
            JOptionPane.showMessageDialog(null, "Utilize apenas números inteiros para quantidade.");
        }
    }

    /**
     * Gera atalho de teclas para determinados comandos
     */
    public void geraAcessibilidade() {
        btnCadastrar.setMnemonic(KeyEvent.VK_D);
        btnCancelar.setMnemonic(KeyEvent.VK_C);
    }
}
