package telas;

import classes.EspecialidadeDAO;
import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;

/**Tela aonde será escolhido Especialidade para associar à um Dentista.*/
public class TelaCadastroEspecialidade extends javax.swing.JFrame {

    private TelaPrincipal telaPrincipal;
    private int i = 1;
    private EspecialidadeDAO dao = new EspecialidadeDAO();

    public void MostraTela(TelaPrincipal obj) {
        this.telaPrincipal = obj;
        setVisible(true);
    }

    public TelaCadastroEspecialidade() {
        initComponents();
        lblNome2.setVisible(false);
        cbEspecialidade2.setVisible(false);
        lblNome3.setVisible(false);
        cbEspecialidade3.setVisible(false);
        lblNome4.setVisible(false);
        cbEspecialidade4.setVisible(false);
        btnRemover.setVisible(false);
        geraAcessibilidade();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        lblEspecialidades = new javax.swing.JLabel();
        btnSalvar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        lblNome1 = new javax.swing.JLabel();
        cbEspecialidade1 = new javax.swing.JComboBox<>();
        btnAdicionarMais = new javax.swing.JButton();
        lblNome2 = new javax.swing.JLabel();
        cbEspecialidade2 = new javax.swing.JComboBox<>();
        lblNome3 = new javax.swing.JLabel();
        cbEspecialidade3 = new javax.swing.JComboBox<>();
        lblNome4 = new javax.swing.JLabel();
        cbEspecialidade4 = new javax.swing.JComboBox<>();
        btnRemover = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("SICODON");

        jPanel1.setBackground(new java.awt.Color(239, 235, 235));

        lblEspecialidades.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblEspecialidades.setText("Especialidade(s)");

        btnSalvar.setBackground(new java.awt.Color(30, 48, 112));
        btnSalvar.setFont(new java.awt.Font("Segoe UI", 0, 35)); // NOI18N
        btnSalvar.setForeground(new java.awt.Color(255, 255, 255));
        btnSalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/salvar_.png"))); // NOI18N
        btnSalvar.setText("Salvar");
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });

        btnCancelar.setBackground(new java.awt.Color(30, 48, 112));
        btnCancelar.setFont(new java.awt.Font("Segoe UI", 0, 35)); // NOI18N
        btnCancelar.setForeground(new java.awt.Color(255, 255, 255));
        btnCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/xis_.png"))); // NOI18N
        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        lblNome1.setFont(new java.awt.Font("Segoe UI", 0, 26)); // NOI18N
        lblNome1.setLabelFor(cbEspecialidade1);
        lblNome1.setText("Nome:");

        cbEspecialidade1.setBackground(new java.awt.Color(199, 199, 199));
        cbEspecialidade1.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        cbEspecialidade1.setModel(dao.modeloComboBox());

        btnAdicionarMais.setBackground(new java.awt.Color(40, 75, 165));
        btnAdicionarMais.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        btnAdicionarMais.setForeground(new java.awt.Color(255, 255, 255));
        btnAdicionarMais.setText("Adicionar");
        btnAdicionarMais.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdicionarMaisActionPerformed(evt);
            }
        });

        lblNome2.setFont(new java.awt.Font("Segoe UI", 0, 26)); // NOI18N
        lblNome2.setLabelFor(cbEspecialidade2);
        lblNome2.setText("Nome:");

        cbEspecialidade2.setBackground(new java.awt.Color(199, 199, 199));
        cbEspecialidade2.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        cbEspecialidade2.setModel(dao.modeloComboBox());

        lblNome3.setFont(new java.awt.Font("Segoe UI", 0, 26)); // NOI18N
        lblNome3.setLabelFor(cbEspecialidade3);
        lblNome3.setText("Nome:");

        cbEspecialidade3.setBackground(new java.awt.Color(199, 199, 199));
        cbEspecialidade3.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        cbEspecialidade3.setModel(dao.modeloComboBox());

        lblNome4.setFont(new java.awt.Font("Segoe UI", 0, 26)); // NOI18N
        lblNome4.setLabelFor(cbEspecialidade4);
        lblNome4.setText("Nome:");

        cbEspecialidade4.setBackground(new java.awt.Color(199, 199, 199));
        cbEspecialidade4.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        cbEspecialidade4.setModel(dao.modeloComboBox());

        btnRemover.setBackground(new java.awt.Color(40, 75, 165));
        btnRemover.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        btnRemover.setForeground(new java.awt.Color(255, 255, 255));
        btnRemover.setText("Remover");
        btnRemover.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoverActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblEspecialidades)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lblNome4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(cbEspecialidade4, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblNome2)
                                    .addComponent(lblNome1))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cbEspecialidade1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cbEspecialidade2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lblNome3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(cbEspecialidade3, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(17, 17, 17))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btnAdicionarMais, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnRemover, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btnSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 14, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(lblEspecialidades)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNome1)
                    .addComponent(cbEspecialidade1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNome2)
                    .addComponent(cbEspecialidade2, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNome3)
                    .addComponent(cbEspecialidade3, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNome4)
                    .addComponent(cbEspecialidade4, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAdicionarMais, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnRemover, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 12, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        dispose();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnAdicionarMaisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdicionarMaisActionPerformed
        i++;
        switch (i) {
            case 2:
                lblNome2.setVisible(true);
                cbEspecialidade2.setVisible(true);
                break;
            case 3:
                lblNome3.setVisible(true);
                cbEspecialidade3.setVisible(true);
                break;
            case 4:
                lblNome4.setVisible(true);
                cbEspecialidade4.setVisible(true);
                break;
            default:
                break;
        }
        if (lblNome4.isVisible() == true) {
            btnAdicionarMais.setVisible(false);
        }
        btnRemover.setVisible(true);
    }//GEN-LAST:event_btnAdicionarMaisActionPerformed

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
        salvaNovasEspecialidades();
    }//GEN-LAST:event_btnSalvarActionPerformed

    private void btnRemoverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoverActionPerformed
        switch (i) {
            case 2:
                lblNome2.setVisible(false);
                cbEspecialidade2.setVisible(false);
                break;
            case 3:
                lblNome3.setVisible(false);
                cbEspecialidade3.setVisible(false);
                break;
            case 4:
                lblNome4.setVisible(false);
                cbEspecialidade4.setVisible(false);
                break;
            default:
                break;
        }
        if (lblNome4.isVisible() == false) {
            btnAdicionarMais.setVisible(true);
        }
        if (i == 2) {
            btnRemover.setVisible(false);
        }
        i--;
    }//GEN-LAST:event_btnRemoverActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroEspecialidade.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroEspecialidade.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroEspecialidade.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroEspecialidade.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaCadastroEspecialidade().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdicionarMais;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnRemover;
    private javax.swing.JButton btnSalvar;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> cbEspecialidade1;
    private javax.swing.JComboBox<String> cbEspecialidade2;
    private javax.swing.JComboBox<String> cbEspecialidade3;
    private javax.swing.JComboBox<String> cbEspecialidade4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblEspecialidades;
    private javax.swing.JLabel lblNome1;
    private javax.swing.JLabel lblNome2;
    private javax.swing.JLabel lblNome3;
    private javax.swing.JLabel lblNome4;
    // End of variables declaration//GEN-END:variables

    /**
     * Salva até quatro especialidades para um dentista selecionado.
     */
    public void salvaNovasEspecialidades() {
        int resposta, idDentista, idEspecialidade;
        boolean status;

        String nomeEspecialidade1 = cbEspecialidade1.getSelectedItem().toString();
        idDentista = telaPrincipal.retornaIdDentistaSelecionado();
        idEspecialidade = dao.retornaIdEspecialidade(nomeEspecialidade1);
        status = dao.conectar();
        if (status == false) {
            JOptionPane.showMessageDialog(null, "Erro de conexão.");
        } else {
            resposta = dao.salvar(idDentista, idEspecialidade);
            switch (resposta) {
                case 1:
                    telaPrincipal.atualizaTabelaDentista();
                    JOptionPane.showMessageDialog(null, "Cadastro de especialidade efetuado com sucesso.");
                    break;
                case 1062:
                    JOptionPane.showMessageDialog(null, "Dentista já possui a especialidade " + nomeEspecialidade1 + ".");
                    break;
                default:
                    JOptionPane.showMessageDialog(null, "Erro ao tentar salvar dado.");
                    break;
            }
        }

        if (cbEspecialidade2.isVisible() == true) {
            String nomeEspecialidade2 = cbEspecialidade2.getSelectedItem().toString();

            if (status == false) {

            } else {
                resposta = dao.salvar(idDentista, dao.retornaIdEspecialidade(nomeEspecialidade2));
                switch (resposta) {
                    case 1:
                        break;
                    case 1062:
                        JOptionPane.showMessageDialog(null, "Dentista já possui a especialidade " + nomeEspecialidade2 + ".");
                        break;
                    default:
                        break;
                }
            }
        }
        if (cbEspecialidade3.isVisible() == true) {
            String nomeEspecialidade3 = cbEspecialidade3.getSelectedItem().toString();

            if (status == false) {

            } else {
                resposta = dao.salvar(idDentista, dao.retornaIdEspecialidade(nomeEspecialidade3));
                switch (resposta) {
                    case 1:
                        telaPrincipal.atualizaTabelaDentista();
                        break;
                    case 1062:
                        JOptionPane.showMessageDialog(null, "Dentista já possui a especialidade " + nomeEspecialidade3 + ".");
                        break;
                    default:
                        break;
                }
            }
        }
        if (cbEspecialidade4.isVisible() == true) {
            String nomeEspecialidade4 = cbEspecialidade4.getSelectedItem().toString();
            if (status == false) {

            } else {
                resposta = dao.salvar(idDentista, dao.retornaIdEspecialidade(nomeEspecialidade4));
                switch (resposta) {
                    case 1:
                        telaPrincipal.atualizaTabelaDentista();
                        break;
                    case 1062:
                        JOptionPane.showMessageDialog(null, "Dentista já possui a especialidade " + nomeEspecialidade4 + ".");
                        break;
                    default:
                        break;
                }
            }
        }
        telaPrincipal.atualizaTabelaDentista();
        dao.desconectar();
        dispose();
    }

    /**
     * Gera atalhao de teclas para determinados comandos
     */
    public void geraAcessibilidade() {
        btnSalvar.setMnemonic(KeyEvent.VK_S);
        btnCancelar.setMnemonic(KeyEvent.VK_C);
        btnAdicionarMais.setMnemonic(KeyEvent.VK_A);
        btnRemover.setMnemonic(KeyEvent.VK_R);
    }
}
